import { Artwork } from './types';

export const DEFAULT_ARTWORKS: Artwork[] = [
  {
    id: "art_pk_1",
    title: "Sohni Mahiwal (The Folk Romance)",
    artist_name: "Ustad Allah Bux",
    artist_bio: "A pioneering legend of Pakistani painting, Ustad Allah Bux is revered for capturing the soul of rural Punjab, its landscape, vibrant folklore, and classical romantic legends on massive canvas oils.",
    year_created: 1948,
    origin_country: "Pakistan",
    origin_city: "Lahore, Pakistan",
    price: 38000,
    medium: "Painting",
    dimensions: "120.0 cm x 95.0 cm",
    rating: 5,
    image_url: "https://upload.wikimedia.org/wikipedia/commons/e/e0/Sohni_crossing_the_river_Chenab_to_meet_her_lover_Mahiwal.jpg",
    audio_description_url: "https://actions.google.com/sounds/v1/ambiences/morning_birds.ogg",
    audio_urdu_url: "https://actions.google.com/sounds/v1/ambiences/night_crickets.ogg",
    text_description: "A breathtaking oil masterpiece portraying Sohni crossing the dark, turbulent waters of the Chenab river using a clay pot to meet her beloved Mahiwal. The dramatic storm clouds and waves are painted with masterly control of light, shadow, and theatrical movement.",
    text_description_urdu: "سوہنی مہیوال استاد اللہ بخش کا ایک رومانوی اور لافانی شاہکار ہے جس میں سوہنی کو کچے گھڑے کی مدد سے دریائے چناب کی تند و تیز لہروں کا مقابلہ کرتے ہوئے دکھایا گیا ہے۔ اس میں پنجاب کے دیہی ثقافتی حسن کو کمال مہارت سے پیش کیا گیا ہے۔",
    is_published: true
  },
  {
    id: "art_pk_2",
    title: "Mystic Calligraphy (Surah Al-Rahman)",
    artist_name: "Syed Sadequain",
    artist_bio: "One of Pakistan's most legendary modernist artists and calligraphers, famous for his energetic, bold calligraphic strokes, massive public murals, and bringing a modern abstract expressionist spirit to traditional Arabic lettering.",
    year_created: 1970,
    origin_country: "Pakistan",
    origin_city: "Karachi, Pakistan",
    price: 55000,
    medium: "Painting",
    dimensions: "145.0 cm x 90.0 cm",
    rating: 5,
    image_url: "https://images.unsplash.com/photo-1564507592333-c60657eea523?q=80&w=800",
    audio_description_url: "https://actions.google.com/sounds/v1/ambiences/morning_birds.ogg",
    audio_urdu_url: "https://actions.google.com/sounds/v1/ambiences/night_crickets.ogg",
    text_description: "An energetic abstract calligraphic masterwork by Sadequain representing verses from Surah Al-Rahman. It features intersecting organic lines and bold ink washes of gold and deep indigo, translating classical spiritual poetry into visual form.",
    text_description_urdu: "صادقین کا صوفیانہ خطاطی کا کام ان کی لاجواب تخلیقی توانائی اور جدید خطاطی کا ایک شاندار نمونہ ہے، جس میں سورہ رحمٰن کی آیات کو سنہرے اور نیلے رنگوں سے روحانی کلام کی بصری تصویر کشی میں تبدیل کیا گیا ہے۔",
    is_published: true
  },
  {
    id: "art_pk_3",
    title: "The Mughal Courtship",
    artist_name: "Abdur Rahman Chughtai",
    artist_bio: "The legendary National Artist of Pakistan, celebrated for creating a distinctive watercolor style that fused traditional Islamic and Persian miniatures with Art Nouveau elegance.",
    year_created: 1940,
    origin_country: "Pakistan",
    origin_city: "Lahore, Pakistan",
    price: 45000,
    medium: "Painting",
    dimensions: "68.2 cm x 49.5 cm",
    rating: 5,
    image_url: "https://images.metmuseum.org/CRDImages/is/original/DP152434.jpg",
    audio_description_url: "https://actions.google.com/sounds/v1/ambiences/morning_birds.ogg",
    audio_urdu_url: "https://actions.google.com/sounds/v1/ambiences/night_crickets.ogg",
    text_description: "A mesmerizing watercolor masterpiece by Chughtai, rendering classical Mughal romance with signature flowing lines and soft, luminescent pastel wash tones. The detailed costumes and botanical elements showcase a unique synthesis of Eastern tradition and modern design.",
    text_description_urdu: "مغل معاشقہ عبدالرحمٰن چغتائی کا ایک سحر انگیز واٹر کلر شاہکار ہے جو مغل دور کی روایات، رنگین ریشمی ملبوسات، اور رومانوی نفاست کو نازک لکیروں اور روایتی خطاطی کے انداز میں پیش کرتا ہے۔",
    is_published: true
  },
  {
    id: "art_pk_4",
    title: "Woman and the Dove",
    artist_name: "Jamil Naqsh",
    artist_bio: "A renowned modern master of Pakistan, Jamil Naqsh spent decades in Karachi painting the female figure and the pigeon, exploring theme variations of love, peace, and domestic tranquility through cubist and calligraphic forms.",
    year_created: 1985,
    origin_country: "Pakistan",
    origin_city: "Karachi, Pakistan",
    price: 29000,
    medium: "Painting",
    dimensions: "100.0 cm x 75.0 cm",
    rating: 4,
    image_url: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?q=80&w=800",
    audio_description_url: "https://actions.google.com/sounds/v1/ambiences/morning_birds.ogg",
    audio_urdu_url: "https://actions.google.com/sounds/v1/ambiences/night_crickets.ogg",
    text_description: "A gorgeous oil study featuring a tranquil female figure holding a dove. Using light pastels and calligraphic brush lines, Naqsh captures a profound sense of serenity, texture, and organic connection.",
    text_description_urdu: "عورت اور فاختہ جمیل نقش کا ایک شاندار ماڈرن آرٹ کا نمونہ ہے جس میں کبوتر اور عورت کے باہمی جوڑ کو صلح اور سکون کی علامت کے طور پر نہایت دلکش اور خلاصہ دار رنگوں میں بنایا گیا ہے۔",
    is_published: true
  },
  {
    id: "art_in_1",
    title: "Shakuntala Looking Back",
    artist_name: "Raja Ravi Varma",
    artist_bio: "A legendary Indian painter who attained universal acclaim for depicting scenes from Sanskrit literature with European academic realism and rich Indian iconography.",
    year_created: 1898,
    origin_country: "India",
    origin_city: "Mumbai, India",
    price: 65000,
    medium: "Painting",
    dimensions: "92.0 cm x 71.0 cm",
    rating: 5,
    image_url: "https://upload.wikimedia.org/wikipedia/commons/c/c5/Raja_Ravi_Varma_-_Shakuntala.jpg",
    audio_description_url: "https://actions.google.com/sounds/v1/ambiences/morning_birds.ogg",
    audio_urdu_url: "https://actions.google.com/sounds/v1/ambiences/night_crickets.ogg",
    text_description: "An iconic Indian painting depicting Shakuntala pretending to remove a thorn from her foot while turning back to catch another glimpse of her beloved Dushyanta. Ravi Varma's masterly control over draped fabrics, natural light, and dramatic expression is fully realized here.",
    text_description_urdu: "شکنتلا راجہ روی ورما کا ایک شاندار ہندوستانی شاہکار ہے جس میں مہابھارت کی شکنتلا کو کانٹے چبھنے کے بہانے مڑ کر اپنے محبوب کو دیکھتے ہوئے کمال مہارت اور رنگینی کے ساتھ دکھایا گیا ہے۔",
    is_published: true
  },
  {
    id: "art_cn_1",
    title: "Sancai Terracotta Warhorse",
    artist_name: "Tang Dynasty Sculptors",
    artist_bio: "The sculptural artisans of the 8th-century Tang Dynasty, who pioneered tri-color ceramic sculpture to capture the powerful energy and imperial elegance of warhorses.",
    year_created: 740,
    origin_country: "China",
    origin_city: "Chang'an (Xi'an), China",
    price: 110000,
    medium: "Clay & Ceramic",
    dimensions: "51.2 cm x 48.0 cm",
    rating: 5,
    image_url: "https://upload.wikimedia.org/wikipedia/commons/b/bd/Tang_glazed_terracotta_horse_A_19228_white_bg.jpg",
    audio_description_url: "https://actions.google.com/sounds/v1/ambiences/morning_birds.ogg",
    audio_urdu_url: "https://actions.google.com/sounds/v1/ambiences/night_crickets.ogg",
    text_description: "An incredibly lifelike Tang Dynasty terracotta horse covered in a rich, dripping Sancai (three-color) lead-silicate glaze. The glaze colors of amber yellow, copper green, and creamy white run down the animal's powerful muscles.",
    text_description_urdu: "تانگ سلطنت کا یہ مٹی کا گھوڑا تین رنگوں کے قیمتی روغن کی بدولت اس عہد کی عظمت، رعب اور بلند مرتبے کو بہترین انداز میں بیان کرتا ہے۔ اس کا تناؤ اور چمک حیران کن ہے۔",
    is_published: true
  },
  {
    id: "art_kr_1",
    title: "Celadon Plum Blossom Meiping",
    artist_name: "Goryeo Dynasty Masters",
    artist_bio: "The anonymous master craftsmen of 12th-century Goryeo Korea, renowned globally for pioneering the ethereal, pale green crackle jade glaze known as Celadon.",
    year_created: 1150,
    origin_country: "Korea",
    origin_city: "Kaesong, Korea",
    price: 85000,
    medium: "Clay & Ceramic",
    dimensions: "34.4 cm x 21.0 cm",
    rating: 5,
    image_url: "https://upload.wikimedia.org/wikipedia/commons/d/d4/Celadon_Prunus_Vase_with_Inlaid_Crane_and_Cloud_Design.jpg",
    audio_description_url: "https://actions.google.com/sounds/v1/ambiences/morning_birds.ogg",
    audio_urdu_url: "https://actions.google.com/sounds/v1/ambiences/night_crickets.ogg",
    text_description: "An exceptional Goryeo Dynasty celadon vase featuring inlaid designs of white cranes soaring among stylised peach blossoms and plum branches. The vessel displays a delicate crackle glaze with a soft, translucent jade-green hue.",
    text_description_urdu: "سلادون پلم بلوسم بارہویں صدی کا ایک شاندار برتن ہے جس پر اڑتے ہوئے سفید بگلوں اور آڑو کے شگفتہ پھولوں کا کام کیا گیا ہے۔ اس کا سبز شفاف روغن بہتے ہوئے پانی اور پاکیزگی کی علامت مانا جاتا ہے۔",
    is_published: true
  },
  {
    id: "art_kr_2",
    title: "Baekja Moon Jar",
    artist_name: "Joseon Dynasty Masters",
    artist_bio: "The royal ceramic masters of the Joseon Dynasty in Korea, famous for creating 'Moon Jars'—asymmetrical white porcelain vessels reflecting Neo-Confucian ideals of simplicity, purity, and naturalness.",
    year_created: 1750,
    origin_country: "Korea",
    origin_city: "Seoul, Korea",
    price: 75000,
    medium: "Clay & Ceramic",
    dimensions: "45.0 cm x 42.0 cm",
    rating: 5,
    image_url: "https://upload.wikimedia.org/wikipedia/commons/8/87/White_porcelain_moon_jar_%28Korea%29.jpg",
    audio_description_url: "https://actions.google.com/sounds/v1/ambiences/morning_birds.ogg",
    audio_urdu_url: "https://actions.google.com/sounds/v1/ambiences/night_crickets.ogg",
    text_description: "A gorgeous Joseon Dynasty white porcelain Moon Jar. Its slightly asymmetrical round body, soft milky white luster, and subtle imperfections represent the zenith of Korean minimalist pottery.",
    text_description_urdu: "سفید چینی مٹی کا چاند مرتبان جوسین سلطنت کے کوریائی برتن سازوں کا ایک منفرد شاہکار ہے جو سادگی، قدرتی حسن اور نفاست کا مظہر مانا جاتا ہے۔ اس کی شکل چودہویں رات کے چاند کی طرح گول اور شفاف ہوتی ہے۔",
    is_published: true
  },
  {
    id: "art_jp_1",
    title: "The Great Wave off Kanagawa",
    artist_name: "Katsushika Hokusai",
    artist_bio: "A Japanese ukiyo-e artist of the Edo period, universally known for his series 'Thirty-Six Views of Mount Fuji' and his composition of powerful waves.",
    year_created: 1831,
    origin_country: "Japan",
    origin_city: "Edo (Tokyo), Japan",
    price: 95000,
    medium: "Painting",
    dimensions: "25.7 cm × 37.9 cm",
    rating: 5,
    image_url: "https://upload.wikimedia.org/wikipedia/commons/0/0d/The_Great_Wave_off_Kanagawa.jpg",
    audio_description_url: "https://actions.google.com/sounds/v1/ambiences/morning_birds.ogg",
    audio_urdu_url: "https://actions.google.com/sounds/v1/ambiences/night_crickets.ogg",
    text_description: "A breathtaking Japanese woodblock print showing an enormous wave threatening three fast-moving boats off the coast of Kanagawa. The powerful wave curves like a claw with foaming droplets of water, framing Mount Fuji.",
    text_description_urdu: "کاناگاوا کی عظیم لہر ہوکوسائی کا دنیا بھر میں پسند کیا جانے والا فن پارہ ہے۔ اس میں ایک تند و تیز لہر کو لکڑی کی کشتیاں نگلتے ہوئے اور پس منظر میں خاموش، برف پوش کوہ فجی کو نہایت نفاست سے دکھایا گیا ہے۔",
    is_published: true
  },
  {
    id: "art_it_1",
    title: "Mona Lisa (La Gioconda)",
    artist_name: "Leonardo da Vinci",
    artist_bio: "A supreme Italian Renaissance polymath, scientist, theorist, sculptor, and architect, Leonardo is globally regarded as one of the greatest painters in human history.",
    year_created: 1503,
    origin_country: "Italy",
    origin_city: "Florence, Italy",
    price: 150000,
    medium: "Painting",
    dimensions: "77.0 cm x 53.0 cm",
    rating: 5,
    image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ec/Mona_Lisa%2C_by_Leonardo_da_Vinci%2C_from_C2RMF_retouched.jpg/800px-Mona_Lisa%2C_by_Leonardo_da_Vinci%2C_from_C2RMF_retouched.jpg",
    audio_description_url: "https://actions.google.com/sounds/v1/ambiences/morning_birds.ogg",
    audio_urdu_url: "https://actions.google.com/sounds/v1/ambiences/night_crickets.ogg",
    text_description: "The Mona Lisa is a half-length portrait painting by Italian artist Leonardo da Vinci. It has been described as 'the best known, the most visited, the most written about, the most sung about, the most parodied work of art in the world'. The painting's novel qualities include the subject's enigmatic expression and the atmospheric background.",
    text_description_urdu: "مونا لیزا اطالوی نشاۃ الثانیہ کے عظیم ترین مصور لیونارڈو ڈا ونچی کا وہ لافانی شاہکار ہے جو دنیا بھر میں اپنی پراسرار مسکراہٹ، گہرے سحر انگیز تاثرات اور منفرد پس منظر کی روشنیوں کی بدولت مانا جاتا ہے۔",
    is_published: true
  },
  {
    id: "art_it_2",
    title: "The Birth of Venus",
    artist_name: "Sandro Botticelli",
    artist_bio: "An outstanding Italian painter of the Early Renaissance, Sandro Botticelli is famous for his exquisite, lyrical depictions of mythological and classical themes under Medici patronage.",
    year_created: 1485,
    origin_country: "Italy",
    origin_city: "Florence, Italy",
    price: 120000,
    medium: "Painting",
    dimensions: "172.5 cm x 278.5 cm",
    rating: 5,
    image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0b/Sandro_Botticelli_-_La_nascita_di_Venere_-_Google_Art_Project_-_edited.jpg/800px-Sandro_Botticelli_-_La_nascita_di_Venere_-_Google_Art_Project_-_edited.jpg",
    audio_description_url: "https://actions.google.com/sounds/v1/ambiences/morning_birds.ogg",
    audio_urdu_url: "https://actions.google.com/sounds/v1/ambiences/night_crickets.ogg",
    text_description: "A monumental Early Renaissance painting depicting the goddess Venus emerging from the sea-foam as a fully grown woman, arriving at the shore-side on a giant scallop shell. Zephyrus, the west wind, blows her forward, while Hora, a goddess of the seasons, waits with a flower-strewn cloak.",
    text_description_urdu: "وینس کی پیدائش اطالوی مصور سینڈرو بوٹیسیلی کی ایک انتہائی خوبصورت اور جذباتی تصویر کشی ہے، جس میں محبت اور حسن کی دیوی وینس کو سمندر کے جھاگ سے نکل کر ایک بڑے صدف پر سوار ساحل کی طرف آتے ہوئے دکھایا گیا ہے۔",
    is_published: true
  },
  {
    id: "art_ir_1",
    title: "The Court of Keyumars",
    artist_name: "Sultan Muhammad",
    artist_bio: "The premier master painter of the Safavid school of Persian miniature painting, active in Tabriz, renowned for his vibrant, densely detailed depictions of spiritual, heroic, and royal Persian narratives.",
    year_created: 1522,
    origin_country: "Iran",
    origin_city: "Tabriz, Iran",
    price: 135000,
    medium: "Painting",
    dimensions: "47.0 cm x 32.0 cm",
    rating: 5,
    image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/02/Sultan_Muhammad._The_Court_of_Keyumars._ca._1522-1525_Metropolitan_Museum_of_Art%2C_New_York.jpg/800px-Sultan_Muhammad._The_Court_of_Keyumars._ca._1522-1525_Metropolitan_Museum_of_Art%2C_New_York.jpg",
    audio_description_url: "https://actions.google.com/sounds/v1/ambiences/morning_birds.ogg",
    audio_urdu_url: "https://actions.google.com/sounds/v1/ambiences/night_crickets.ogg",
    text_description: "Widely regarded as one of the absolute zeniths of Persian miniature painting, this page from the Shahnameh of Shah Tahmasp depicts Keyumars, the legendary first king of Iran, ruling from his mountain top surrounded by his court, wild beasts, and lush, fantastic multi-hued clouds.",
    text_description_urdu: "دربار کیومرث ایرانی مینی ایچر مصوری کا ایک شاندار عروج ہے۔ یہ شاہنامہ شاہ تہماسپ کا ایک دلکش ورق ہے جس میں ایران کے پہلے افسانوی بادشاہ کیومرث کو اپنے درباریوں اور جنگلی جانوروں کے ساتھ پہاڑی چوٹی پر جلوہ افروز دکھایا گیا ہے۔",
    is_published: true
  },
  {
    id: "art_ir_2",
    title: "Safavid Lustreware Bowl",
    artist_name: "Isfahan Pottery Masters",
    artist_bio: "The skilled 17th-century ceramicists of Isfahan, Persia, who revived ancient metallic lustreware techniques to create exquisite pottery reflecting Safavid elegance and floral delicacy.",
    year_created: 1675,
    origin_country: "Iran",
    origin_city: "Isfahan, Iran",
    price: 65000,
    medium: "Clay & Ceramic",
    dimensions: "24.0 cm diameter",
    rating: 5,
    image_url: "https://upload.wikimedia.org/wikipedia/commons/7/77/Persian_plate_with_floral_motifs_17th_century.jpg",
    audio_description_url: "https://actions.google.com/sounds/v1/ambiences/morning_birds.ogg",
    audio_urdu_url: "https://actions.google.com/sounds/v1/ambiences/night_crickets.ogg",
    text_description: "An authentic Safavid dynasty ceramic lustreware bowl showing delicate cobalt blue floral motifs on a brilliant pearlescent glaze. This masterpiece represents the synthesis of traditional Persian patterns with global trade influences.",
    text_description_urdu: "صفوی دور کا یہ چمکدار برتن اصفہان کے ماہر برتن سازوں کی کمال مہارت کا منہ بولتا ثبوت ہے۔ اس پر بنے ہوئے نیلے اور سنہرے پھولوں کے نقش و نگار صفوی جمالیات اور ثقافتی نفاست کا ایک شاہکار ہیں۔",
    is_published: true
  },
  {
    id: "art_cn_2",
    title: "A Thousand Li of Rivers and Mountains",
    artist_name: "Wang Ximeng",
    artist_bio: "A legendary child prodigy of the Song Dynasty court, Wang Ximeng painted this monumental masterpiece at the tender age of 18, under the direct personal tutelage of Emperor Huizong.",
    year_created: 1113,
    origin_country: "China",
    origin_city: "Kaifeng, China",
    price: 140000,
    medium: "Painting",
    dimensions: "51.5 cm x 1191.5 cm",
    rating: 5,
    image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/ca/A_Thousand_Li_of_Rivers_and_Mountains_%28Wang_Ximeng%29.jpg/800px-A_Thousand_Li_of_Rivers_and_Mountains_%28Wang_Ximeng%29.jpg",
    audio_description_url: "https://actions.google.com/sounds/v1/ambiences/morning_birds.ogg",
    audio_urdu_url: "https://actions.google.com/sounds/v1/ambiences/night_crickets.ogg",
    text_description: "One of the greatest masterpieces of traditional Chinese painting, this handscroll stretches nearly twelve meters. It captures sweeping, breathtaking mountain peaks and infinite river valleys in brilliant, mineral-based blue and green pigments.",
    text_description_urdu: "دریاؤں اور پہاڑوں کا ایک ہزار لی چینی مصوری کا ایک لازوال شاہکار ہے جسے وانگ شیمینگ نے صرف اٹھارہ سال کی عمر میں شہنشاہ کی سرپرستی میں تخلیق کیا تھا۔ اس میں چمکدار سبز اور نیلے رنگوں سے پہاڑی چوٹیوں کی شاندار عکاسی کی گئی ہے۔",
    is_published: true
  },
  {
    id: "art_eg_1",
    title: "The Golden Mask of Tutankhamun",
    artist_name: "Ancient Egyptian Royal Goldsmiths",
    artist_bio: "The elite state artisans of the New Kingdom's Eighteenth Dynasty, whose metallurgy and lapidary skill reached unparalleled sophistication in creating royal funerary treasures.",
    year_created: -1323,
    origin_country: "Egypt",
    origin_city: "Thebes, Egypt",
    price: 180000,
    medium: "Clay & Ceramic",
    dimensions: "54.0 cm x 39.3 cm",
    rating: 5,
    image_url: "https://upload.wikimedia.org/wikipedia/commons/3/38/Tutankhamun_tomb_artifact_mask_profile.jpg",
    audio_description_url: "https://actions.google.com/sounds/v1/ambiences/morning_birds.ogg",
    audio_urdu_url: "https://actions.google.com/sounds/v1/ambiences/night_crickets.ogg",
    text_description: "An iconic gold death mask inlaid with semi-precious stones, including lapis lazuli, carnelian, obsidian, and colored glass. It portrays the young pharaoh Tutankhamun in the likeness of Osiris, god of the afterlife.",
    text_description_urdu: "توت عنخ آمون کا سنہرا ماسک قدیم مصر کی اعلیٰ ترین دھات کاری اور شاہی فن کا عروج ہے، جس میں لاجورد اور قیمتی پتھروں کی مدد سے ابدی زندگی کے تاثرات تراشے گئے ہیں۔",
    is_published: true
  },
  {
    id: "art_gr_1",
    title: "The Winged Victory of Samothrace",
    artist_name: "Hellenistic Sculptors",
    artist_bio: "The anonymous master sculptors of the 2nd century BC, celebrated for capturing dramatic movement, light, and fluid drapery in heavy Parian marble.",
    year_created: -190,
    origin_country: "Greece",
    origin_city: "Samothrace, Greece",
    price: 155000,
    medium: "Painting",
    dimensions: "244.0 cm height",
    rating: 5,
    image_url: "https://upload.wikimedia.org/wikipedia/commons/c/ce/Victoire_de_Samothrace_-_Louvre_Museum_-_May_2015.jpg",
    audio_description_url: "https://actions.google.com/sounds/v1/ambiences/morning_birds.ogg",
    audio_urdu_url: "https://actions.google.com/sounds/v1/ambiences/night_crickets.ogg",
    text_description: "A monumental marble sculpture of Nike, the Greek goddess of victory, standing on a ship's prow with her garments blowing in the sea wind. It is one of the world's absolute masterpieces of Hellenistic movement and emotion.",
    text_description_urdu: "ساموتھریس کی پروں والی فتح یونانی فنِ سنگ تراشی کا ایک بے مثال اور متحرک شاہکار ہے جس میں ہوا کے دوش پر اڑتی ہوئی دیوی نائیکی کی لہراتی ہوئی پوشاک کو سنگِ مرمر میں ڈھالا گیا ہے۔",
    is_published: true
  },
  {
    id: "art_tr_1",
    title: "Iznik Tulip Tiles Panel",
    artist_name: "Iznik Court Potters",
    artist_bio: "The imperial ceramicists of 16th-century Iznik, renowned for inventing brilliant underglaze tomato-reds and deep cobalt blues under a sparkling, glass-like quartz glaze.",
    year_created: 1575,
    origin_country: "Turkey",
    origin_city: "Iznik, Turkey",
    price: 68000,
    medium: "Clay & Ceramic",
    dimensions: "84.0 cm x 62.0 cm",
    rating: 5,
    image_url: "https://upload.wikimedia.org/wikipedia/commons/b/b3/Iznik_tile_panel_Louvre_OA3919_n1.jpg",
    audio_description_url: "https://actions.google.com/sounds/v1/ambiences/morning_birds.ogg",
    audio_urdu_url: "https://actions.google.com/sounds/v1/ambiences/night_crickets.ogg",
    text_description: "An exquisite ceramic tile panel depicting a vibrant, swirling garden of blooming red tulips and carnations. Underglaze painted in cobalt blue, turquoise, and signature Iznik sealing-wax red.",
    text_description_urdu: "ازنک کے شاہی برتن سازوں کی تیار کردہ یہ خوبصورت ٹائلیں عثمانی دورِ حکومت میں پھولوں کی جمالیات، گہرے سرخ اور نیلے روغن کی چمک کا بہترین نمونہ ہیں۔",
    is_published: true
  },
  {
    id: "art_fr_1",
    title: "Impression, Sunrise",
    artist_name: "Claude Monet",
    artist_bio: "The founding father of French Impressionist painting, who revolutionized fine art by focusing on capturing transient light, atmospheric moods, and immediate optical sensations over strict realism.",
    year_created: 1872,
    origin_country: "France",
    origin_city: "Paris, France",
    price: 130000,
    medium: "Painting",
    dimensions: "48.0 cm x 63.0 cm",
    rating: 5,
    image_url: "https://upload.wikimedia.org/wikipedia/commons/5/5c/Claude_Monet%2C_Impression%2C_soleil_levant.jpg",
    audio_description_url: "https://actions.google.com/sounds/v1/ambiences/morning_birds.ogg",
    audio_urdu_url: "https://actions.google.com/sounds/v1/ambiences/night_crickets.ogg",
    text_description: "The legendary oil painting that gave the Impressionist movement its name. It depicts the port of Le Havre at dawn with a striking orange sun rising above hazy blue ship masts and soft water ripples.",
    text_description_urdu: "کلود مونے کا یہ تاریخی آئل پینٹنگ آرٹ میں تاثریت پسند تحریک کی شروعات مانا جاتا ہے۔ اس میں صبح سویرے بندرگاہ پر طلوع ہوتے ہوئے سورج کی دھیمی روشنی اور نیلے سائے کو انتہائی خوبصورت انداز میں پیش کیا گیا ہے۔",
    is_published: true
  },
  {
    id: "art_es_1",
    title: "Las Meninas (The Ladies-in-Waiting)",
    artist_name: "Diego Velázquez",
    artist_bio: "The leading artist of the Spanish Golden Age, Velázquez served as King Philip IV's court painter, acclaimed for his incredible virtuosity in optical realism and complex spatial composition.",
    year_created: 1656,
    origin_country: "Spain",
    origin_city: "Madrid, Spain",
    price: 145000,
    medium: "Painting",
    dimensions: "318.0 cm x 276.0 cm",
    rating: 5,
    image_url: "https://upload.wikimedia.org/wikipedia/commons/3/31/Las_Meninas%2C_by_Diego_Vel%C3%A1zquez%2C_from_Prado_in_Google_Earth.jpg",
    audio_description_url: "https://actions.google.com/sounds/v1/ambiences/morning_birds.ogg",
    audio_urdu_url: "https://actions.google.com/sounds/v1/ambiences/night_crickets.ogg",
    text_description: "A complex and mysterious oil painting representing the Spanish royal family's life. The composition features the young Infanta Margaret Theresa surrounded by her retinue of maids, dwarfs, and the artist himself painting a massive canvas.",
    text_description_urdu: "لاس مینیناس ہسپانوی مصور ڈیگو ویلاسکیز کا سب سے پیچیدہ اور مشہور فن پارہ ہے، جس میں انہوں نے شاہی دربار کے روزمرہ منظر، روشنی کے کمال اور عکس کے جادوئی تال میل کو کینوس پر اتارا ہے۔",
    is_published: true
  },
  {
    id: "art_mx_1",
    title: "The Aztec Sun Stone",
    artist_name: "Tenochtitlan Royal Sculptors",
    artist_bio: "The monumental stonecarving guilds of the Aztec Empire, who carved colossal basalt monuments representing complex cosmological calendars and celestial legends.",
    year_created: 1479,
    origin_country: "Mexico",
    origin_city: "Tenochtitlan, Mexico",
    price: 115000,
    medium: "Clay & Ceramic",
    dimensions: "358 cm diameter",
    rating: 5,
    image_url: "https://upload.wikimedia.org/wikipedia/commons/c/c8/Piedra_del_Sol_en_el_MNA.jpg",
    audio_description_url: "https://actions.google.com/sounds/v1/ambiences/morning_birds.ogg",
    audio_urdu_url: "https://actions.google.com/sounds/v1/ambiences/night_crickets.ogg",
    text_description: "A colossal Aztec basalt monolith representing the five eras of creation and cosmological calendars, centering the face of the sun god Tonatiuh.",
    text_description_urdu: "پتھر کا یہ عظیم الشان سورج چکر قدیم ایزٹیک سلطنت کی فلکیاتی فہم اور کائناتی عقائد کو بیان کرتا ہے، جس کے عین وسط میں سورج دیوتا ٹوناٹیو کا چہرہ نقش ہے۔",
    is_published: true
  },
  {
    id: "art_pe_1",
    title: "Moche Portrait Ceramic Vessel",
    artist_name: "Moche Ceramic Guilds",
    artist_bio: "The elite pre-Columbian potters of northern Peru, renowned for their incredibly lifelike three-dimensional portrait vessels capturing individual human faces with rich clay glazes.",
    year_created: 500,
    origin_country: "Peru",
    origin_city: "Trujillo, Peru",
    price: 72000,
    medium: "Clay & Ceramic",
    dimensions: "27.5 cm x 18.0 cm",
    rating: 5,
    image_url: "https://upload.wikimedia.org/wikipedia/commons/c/cb/Moche_portrait_vessel_Larco_Museum_ML001258.jpg",
    audio_description_url: "https://actions.google.com/sounds/v1/ambiences/morning_birds.ogg",
    audio_urdu_url: "https://actions.google.com/sounds/v1/ambiences/night_crickets.ogg",
    text_description: "An exceptionally realistic pre-Columbian clay portrait jar representing a Moche ruler or noble with highly detailed face paint and headgear.",
    text_description_urdu: "موچے تہذیب کا یہ مٹی کا برتن انسانی چہرے کی تین رخی تصویر کشی کا ایک نادر ترین نمونہ ہے، جس میں اس دور کے حکمران کے تاثرات اور سر کی آرائش کو نہایت نفاست سے دکھایا گیا ہے۔",
    is_published: true
  },
  {
    id: "art_iq_1",
    title: "Lion of the Processional Way",
    artist_name: "Babylonian Royal Sculptors",
    artist_bio: "The imperial architectural brickmakers under Nebuchadnezzar II, who pioneered molded and brightly colored glazed brick relief panels to adorn Babylon's sacred avenues.",
    year_created: -575,
    origin_country: "Iraq",
    origin_city: "Babylon, Iraq",
    price: 125000,
    medium: "Clay & Ceramic",
    dimensions: "122.0 cm x 228.0 cm",
    rating: 5,
    image_url: "https://upload.wikimedia.org/wikipedia/commons/4/41/Glazed_brick_relief_of_a_lion_from_the_Processional_Way%2C_Babylon_-_Pergamon_Museum.jpg",
    audio_description_url: "https://actions.google.com/sounds/v1/ambiences/morning_birds.ogg",
    audio_urdu_url: "https://actions.google.com/sounds/v1/ambiences/night_crickets.ogg",
    text_description: "A magnificent glazed brick relief panel depicting a roaring lion, originally lining the sacred Processional Way leading to the Ishtar Gate of ancient Babylon.",
    text_description_urdu: "قدیم بابل کے شاہی راستوں کی شان بڑھانے والے اس چمکدار اینٹوں کے ریلیف میں بابل کے غراتے ہوئے شیر کو کمال دلیری اور رنگین چمکدار پالش کے ساتھ دکھایا گیا ہے۔",
    is_published: true
  },
  {
    id: "art_sy_1",
    title: "Calligraphic Lustreware Plate",
    artist_name: "Raqqa Ceramic Artisans",
    artist_bio: "The famed medieval potters of Raqqa, Syria, who created shimmering underglaze lusterwares decorated with fluid Arabic inscriptions during the Abbasid Golden Age.",
    year_created: 1220,
    origin_country: "Syria",
    origin_city: "Raqqa, Syria",
    price: 64000,
    medium: "Clay & Ceramic",
    dimensions: "28.5 cm diameter",
    rating: 5,
    image_url: "https://upload.wikimedia.org/wikipedia/commons/e/ee/Raqqa_fritware_bowl_Met_56.185.jpg",
    audio_description_url: "https://actions.google.com/sounds/v1/ambiences/morning_birds.ogg",
    audio_urdu_url: "https://actions.google.com/sounds/v1/ambiences/night_crickets.ogg",
    text_description: "A beautiful medieval Syrian ceramic plate painted with flowing calligraphic script in iridescent luster glaze over cobalt blue highlights.",
    text_description_urdu: "رَقّہ کا یہ صوفیانہ برتن عربی خطاطی کے حروف اور چمکدار سنہرے روغن کے ملاپ سے تیار کیا گیا ہے جو عباسی دورِ خلافت کے صوفیانہ حسن کو بیان کرتا ہے۔",
    is_published: true
  }
];
