import { Artwork } from "./types";

// Contemporary Pakistani paintings curated from Artmajeur's Pakistan painters
// gallery (artmajeur.com/en/artists/painters?country=PK). Images are served
// from Artmajeur's own CDN; titles, artists and media come from the listings.
// Guide descriptions are hand-written curation notes, not API-generated text.

const AMBIENT_EN = "https://actions.google.com/sounds/v1/ambiences/morning_birds.ogg";
const AMBIENT_UR = "https://actions.google.com/sounds/v1/ambiences/night_crickets.ogg";

const base = {
  origin_country: "Pakistan",
  medium: "Painting" as const,
  rating: 5,
  audio_description_url: AMBIENT_EN,
  audio_urdu_url: AMBIENT_UR,
  is_published: true,
};

export const PAKISTAN_ARTWORKS: Artwork[] = [
  {
    ...base,
    id: "pk_am_1",
    title: "Ayatul Kursi and Durood Shareef",
    artist_name: "Sajid Hussain",
    artist_bio: "A contemporary Pakistani calligraphy painter whose acrylic canvases carry Quranic verses in flowing modern khattati scripts.",
    year_created: 2025,
    origin_city: "Pakistan",
    dimensions: "48.3 cm x 68.6 cm",
    image_url: "https://medias.artmajeur.com/standard/20093491_ayatul-kursi-and-durood-shareef-painting-by-sajid-hussain-1.jpg",
    text_description: "Ayatul Kursi — the Throne Verse — is among the most beloved passages of the Quran, recited daily in millions of Pakistani homes for protection and peace. Sajid Hussain renders it in sweeping acrylic calligraphy, letting the sacred letterforms rise and interlock like architecture, so the verse itself becomes the monument.",
    text_description_urdu: "آیت الکرسی قرآن پاک کی سب سے محبوب آیات میں سے ہے جو ہر پاکستانی گھر میں حفاظت اور سکون کے لیے پڑھی جاتی ہے۔ ساجد حسین نے اسے بہتی ہوئی خطاطی میں یوں ڈھالا ہے کہ حروف خود ایک عمارت کی مانند بلند ہوتے دکھائی دیتے ہیں۔",
  },
  {
    ...base,
    id: "pk_am_2",
    title: "Surah Rahman Painting",
    artist_name: "Sajid Hussain",
    artist_bio: "A contemporary Pakistani calligraphy painter whose acrylic canvases carry Quranic verses in flowing modern khattati scripts.",
    year_created: 2025,
    origin_city: "Pakistan",
    dimensions: "Dimensions variable",
    image_url: "https://medias.artmajeur.com/standard/19806628_surah-rehman-painting-1.jpg",
    text_description: "Surah Al-Rahman, often called the 'Bride of the Quran' for its refrain-like beauty, has inspired Pakistani calligraphers from Sadequain to the present day. Hussain's acrylic treatment continues that lineage, weaving the chapter's rhythmic verses into layered pigment where devotion and design breathe together.",
    text_description_urdu: "سورہ رحمٰن جسے اپنی نغمگی کے باعث قرآن کی دلہن کہا جاتا ہے، صادقین سے آج تک پاکستانی خطاطوں کی تحریک رہی ہے۔ حسین کا یہ کینوس اسی روایت کا تسلسل ہے جہاں عقیدت اور فن ایک ساتھ سانس لیتے ہیں۔",
  },
  {
    ...base,
    id: "pk_am_3",
    title: "Asma ul Husna Geometric Calligraphy",
    artist_name: "Sajid Hussain",
    artist_bio: "A contemporary Pakistani calligraphy painter whose acrylic canvases carry Quranic verses in flowing modern khattati scripts.",
    year_created: 2025,
    origin_city: "Pakistan",
    dimensions: "Dimensions variable",
    image_url: "https://medias.artmajeur.com/standard/20075509_asma-ul-husna-geometric-calligraphy-1.jpg",
    text_description: "The ninety-nine names of God — Asma ul Husna — arranged here as geometric calligraphy, a tradition reaching back to Islamic tile-work and manuscript illumination. Hussain disciplines the sacred names into a lattice of order and repetition, echoing the mosque facades of Lahore and Multan in contemporary acrylic.",
    text_description_urdu: "اسمائے حسنیٰ یعنی اللہ کے ننانوے نام یہاں ہندسی خطاطی میں ترتیب دیے گئے ہیں، ایک ایسی روایت جو اسلامی کاشی کاری اور مخطوطات کی زینت سے جا ملتی ہے۔ لاہور اور ملتان کی مساجد کی جھلک جدید رنگوں میں اتر آئی ہے۔",
  },
  {
    ...base,
    id: "pk_am_4",
    title: "SHELBY",
    artist_name: "Sharmene Yousuf (Meneartiste)",
    artist_bio: "A Pakistani oil painter working under the name Meneartiste, known for luminous, texture-rich abstract and figurative canvases.",
    year_created: 2025,
    origin_city: "Pakistan",
    dimensions: "79 cm x 59.4 cm",
    image_url: "https://medias.artmajeur.com/standard/19563271_img-0090.jpg",
    text_description: "In 'SHELBY', Sharmene Yousuf works oil paint the way Pakistan's modernists worked light — building the subject from warm, deliberate strokes until presence emerges from pigment. Her canvases sit in the contemporary current of Karachi's thriving gallery scene, where portraiture and abstraction constantly trade places.",
    text_description_urdu: "شیلبی میں شرمین یوسف تیل کے رنگوں سے روشنی تراشتی ہیں، گرم اور سوچے سمجھے برش اسٹروکس سے تصویر آہستہ آہستہ جیتی جاگتی صورت اختیار کرتی ہے۔ یہ کینوس کراچی کے معاصر فن کی زندہ روایت کا حصہ ہے۔",
  },
  {
    ...base,
    id: "pk_am_5",
    title: "Emerald Ribbon",
    artist_name: "Sharmene Yousuf (Meneartiste)",
    artist_bio: "A Pakistani oil painter working under the name Meneartiste, known for luminous, texture-rich abstract and figurative canvases.",
    year_created: 2025,
    origin_city: "Pakistan",
    dimensions: "Dimensions variable",
    image_url: "https://medias.artmajeur.com/standard/19425316_img-0357.jpg",
    text_description: "A ribbon of emerald unspools across the canvas — green, the colour that carries deep national and spiritual resonance in Pakistan, here freed into pure abstraction. Yousuf lets the hue move like silk in wind, an oil meditation on colour as emotion rather than description.",
    text_description_urdu: "زمرد کی ایک لہر کینوس پر بکھرتی ہے — سبز رنگ جو پاکستان میں روحانی اور قومی معنویت رکھتا ہے، یہاں خالص تجرید میں آزاد کر دیا گیا ہے۔ رنگ ریشم کی طرح ہوا میں لہراتا محسوس ہوتا ہے۔",
  },
  {
    ...base,
    id: "pk_am_6",
    title: "Land Of The Living IV",
    artist_name: "Shaheera Saeed",
    artist_bio: "A Pakistani oil painter whose 'Land of the Living' series contemplates landscape, memory and belonging.",
    year_created: 2025,
    origin_city: "Pakistan",
    dimensions: "Dimensions variable",
    image_url: "https://medias.artmajeur.com/standard/18903175_photo-1747591097008.jpg",
    text_description: "The fourth canvas in Saeed's 'Land of the Living' series carries forward Pakistan's long conversation between land and painter — from the Punjab plains of Ustad Allah Bux to today's contemporary landscape practice. Oil paint becomes soil and horizon, a remembered geography as much as an observed one.",
    text_description_urdu: "شہیرہ سعید کی سیریز کا یہ چوتھا کینوس زمین اور مصور کے اُس دیرینہ مکالمے کو آگے بڑھاتا ہے جو استاد اللہ بخش کے پنجاب سے آج تک جاری ہے۔ تیل کے رنگ مٹی اور افق بن جاتے ہیں، ایک یاد کی ہوئی جغرافیہ۔",
  },
  {
    ...base,
    id: "pk_am_7",
    title: "GOLDEN",
    artist_name: "Shaheera Saeed",
    artist_bio: "A Pakistani oil painter whose 'Land of the Living' series contemplates landscape, memory and belonging.",
    year_created: 2024,
    origin_city: "Pakistan",
    dimensions: "Dimensions variable",
    image_url: "https://medias.artmajeur.com/standard/16964857_dsc-0614-edited-color-tem-crop-re.jpg",
    text_description: "'GOLDEN' bathes its subject in the late-afternoon light familiar to anyone who has watched the sun drop over Pakistani fields at harvest. Saeed's oils hold that hour still — warm, grain-heavy, unhurried — turning an everyday radiance into something devotional.",
    text_description_urdu: "گولڈن اُس سنہری سہ پہر کی روشنی کو قید کرتا ہے جو فصل کٹائی کے موسم میں پاکستانی کھیتوں پر اترتی ہے۔ سعید کے رنگ اس گھڑی کو تھام لیتے ہیں — گرم، ٹھہری ہوئی، اور عبادت جیسی۔",
  },
  {
    ...base,
    id: "pk_am_8",
    title: "Mysticism 2",
    artist_name: "Asim Amjad Tippu",
    artist_bio: "A Pakistani painter in acrylic and oil whose work explores mysticism, the pandemic age, and inner landscapes.",
    year_created: 2020,
    origin_city: "Pakistan",
    dimensions: "Dimensions variable",
    image_url: "https://medias.artmajeur.com/standard/13313168_img-20200312-222507.jpg",
    text_description: "Pakistan's art has always kept one door open to the mystical — the Sufi current running from shrine qawwali to Sadequain's ecstatic line. Tippu's 'Mysticism 2' enters through that door in acrylic, dissolving figure into feeling the way a dhamaal dissolves the dancer into the drum.",
    text_description_urdu: "پاکستانی فن نے ہمیشہ تصوف کے لیے ایک دروازہ کھلا رکھا ہے — درگاہوں کی قوالی سے صادقین کی وجدانی لکیر تک۔ ٹیپو کا یہ کینوس اسی دروازے سے داخل ہوتا ہے جہاں صورت کیفیت میں گھل جاتی ہے۔",
  },
  {
    ...base,
    id: "pk_am_9",
    title: "In Search of Another World",
    artist_name: "Asim Amjad Tippu",
    artist_bio: "A Pakistani painter in acrylic and oil whose work explores mysticism, the pandemic age, and inner landscapes.",
    year_created: 2016,
    origin_city: "Pakistan",
    dimensions: "Dimensions variable",
    image_url: "https://medias.artmajeur.com/standard/10697665_img-20160206-wa0002.jpg",
    text_description: "An oil reverie about departure and longing — themes that sit deep in Pakistani poetry from Iqbal's soaring falcon to Faiz's distant dawn. Tippu paints the search itself: a world half-formed at the edge of the canvas, always one brushstroke out of reach.",
    text_description_urdu: "جدائی اور جستجو پر ایک خواب جیسا کینوس — وہی موضوع جو اقبال کے شاہین سے فیض کی صبحِ وطن تک اردو شاعری میں رچا بسا ہے۔ ٹیپو خود تلاش کو مصور کرتے ہیں، ایک ادھورا جہاں جو ہمیشہ ایک برش اسٹروک دور رہتا ہے۔",
  },
  {
    ...base,
    id: "pk_am_10",
    title: "Mother and Child",
    artist_name: "Tashfeen Rizwan",
    artist_bio: "A Pakistani painter working in pastel and oil, drawn to intimate human subjects and social observation.",
    year_created: 2023,
    origin_city: "Pakistan",
    dimensions: "Dimensions variable",
    image_url: "https://medias.artmajeur.com/standard/16694545_20230323-181040.jpg",
    text_description: "The mother-and-child motif crosses every tradition, but Rizwan's pastel gives it a distinctly South Asian tenderness — the softness of the medium standing in for the softness of the bond. It recalls Chughtai's lyrical figures while speaking in a wholly contemporary, unidealised voice.",
    text_description_urdu: "ماں اور بچے کا موضوع ہر تہذیب میں ملتا ہے مگر رضوان کے پیسٹل رنگ اسے خالص جنوبی ایشیائی نرمی عطا کرتے ہیں — رنگ کی ملائمت رشتے کی ملائمت بن جاتی ہے، چغتائی کی غنائی صورتوں کی بازگشت کے ساتھ۔",
  },
  {
    ...base,
    id: "pk_am_11",
    title: "Solitude and Legacy",
    artist_name: "Tashfeen Rizwan",
    artist_bio: "A Pakistani painter working in pastel and oil, drawn to intimate human subjects and social observation.",
    year_created: 2022,
    origin_city: "Pakistan",
    dimensions: "Dimensions variable",
    image_url: "https://medias.artmajeur.com/standard/16464496_20221230-202846.jpg",
    text_description: "An oil painting that sits with silence — a figure, a space, and the weight of what is handed down. Rizwan's title names the double inheritance of every artist in Lahore's and Karachi's studios today: solitude to work in, and a towering legacy to answer to.",
    text_description_urdu: "یہ کینوس خاموشی کے ساتھ بیٹھتا ہے — ایک وجود، ایک خلا، اور ورثے کا بوجھ۔ تنہائی اور وراثت: ہر پاکستانی مصور کا دوہرا مقدر، کام کے لیے تنہائی اور جواب دہی کے لیے ایک عظیم روایت۔",
  },
];
